# azure-pipelines.yml
trigger:
  branches:
    include:
      - master  # Run the pipeline on the main branch; adjust as necessary

pool:
  name: pc

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.12'  # Use the desired Python version
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    pip install bandit safety  # Install Bandit for code analysis and Safety for dependency CVE checks
  displayName: 'Install dependencies, Bandit, and Safety'

- script: |
    PYTHONPATH=$(System.DefaultWorkingDirectory) pytest tests --junitxml=test-results.xml
  displayName: 'Run tests with pytest'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Pytest Results'
  displayName: 'Publish test results'

- script: |
    bandit -r . -f xml -o bandit-report.xml || true
  displayName: 'Run Bandit security analysis'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/bandit-report.xml'
    failTaskOnFailedTests: false
    testRunTitle: 'Bandit Security Analysis'
  displayName: 'Publish Bandit security analysis results'

- script: |
    safety check --full-report --output text > safety-report.txt || exit 0
  displayName: 'Run CVE scan on dependencies with Safety'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'safety-report.txt'
    artifactName: 'Safety Report'
  displayName: 'Publish Safety CVE report as artifact'

