# azure-pipelines.yml
trigger:
  branches:
    include:
      - master  # Run the pipeline on the main branch; adjust as necessary

pool:
  name: pc

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.12'  # Use the desired Python version
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    pip install bandit pip-audit junit-xml  # Install Bandit for code analysis and pip-audit for dependency CVE checks
    pip install git+https://gabrielmartinez945@dev.azure.com/gabrielmartinez945/pip_audit_to_junit/_git/pip_audit_to_junit  # Install script from Azure DevOps
  displayName: 'Install dependencies, Bandit, pip-audit and conversion script'

- script: |
    PYTHONPATH=$(System.DefaultWorkingDirectory) pytest tests --junitxml=test-results.xml
  displayName: 'Run tests with pytest'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Pytest Results'
  displayName: 'Publish test results'

- script: |
    bandit -r . -f xml -o bandit-report.xml --quiet || true
  displayName: 'Run Bandit security analysis'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/bandit-report.xml'
    failTaskOnFailedTests: false
    testRunTitle: 'Bandit Security Analysis'
  displayName: 'Publish Bandit security analysis results'

- script: |
    pip-audit -r requirements.txt -f json -o pip-audit-report.json || true
  displayName: 'Run CVE scan on dependencies with pip-audit'

- script: |
    python -m pip_audit_to_junit pip-audit-report.json pip-audit-report.xml
  displayName: 'Convert pip-audit JSON to JUnit XML'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/pip-audit-report.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'pip-audit CVE Analysis'
  displayName: 'Publish pip-audit CVE analysis results'